export const english = {
  tawke3y: "Tawke3y",
  tawke3ydes: "Digital Signature Application",
  welcomeback: "Welcome Back!",
  links: "Value Links",
  support: "Social & Support",
  home: "Home",
  signin: "Login",
  register: "Register",
  languageSwitcherButton: "Change Language",
  email: "Email Address",
  password: "Password",
  Enter: "Enter",
  forget: "Forget Password?",
  donot: "Don't Have an account?",
  resetPassword: "Reset Password",
  passwordupdated: "Password Updated",
  fullname: "Full Name",
  user: "Username",
  accountverified: "Account Verified Successfully",
  verify: "Verify Account",
  verifymsg: "Please enter the verification code we sent to",
  verifycode: "Verify Code",
  verifyuser: "Verifying User Data",
  verifyuserdata:
    "Verifying User Data, Please Wait and don't close the browser or stop the verifying process",
  codeverified: "Code Verified Successfully",
  resend: "Resend",
  code: "Didn’t get the code?",
  info: "Info",
  mobile: "Mobile Number",
  address: "Address",
  confirm: "Confirm Password",
  new: "New Password",
  current: "Current Password",
  al: "Already Have an account?",
  type: "Select Type",
  users: "Users",
  logout: "Logout",
  userdet: "User Details",
  signature: "Signatured",
  signatured: "Signatured Contracts",
  notsignatured: "Not Signatured Contracts",
  signcontract: "Sign This Contract",
  sharecontract: "Share Contract",
  viewcontract: "View Contract",
  viewdetails: "View Details",
  viewsignaturedcontracts: "View Signatured Contracts",
  viewnotsignaturedcontracts: "View Not Signatured Contracts",
  send: "Send",
  contractname: "Contract Name",
  profile: "Profile",
  editprofile: "Edit Profile",
  changepass: "Change Password",
  changelang: "Change Language",
  deactivateacc: "Delete Account",
  contracts: "Contracts",
  a: "1",
  b: "2",
  c: "3",
  d: "4",
  id: "Identity Card Number",
  birth: "Birth Date",
  mothername: "Mother's name three parts",
  next: "Next",
  back: "Back",
  save: "Save",
  signed: "Signed at",
  uploaded: "Uploaded at",
  signedby: "Signed by",
  completeprofile: "Complete Profile",
  completeprofileSuccess: "Profile Completed Successfully",
  submit: "Submit",
  errorResponse: "Something Went Wrong!, Please Try Again Later",
  errorsignup: "Error in Registeration!, Please Try Again Later",
  errorcontracts: "Error in retrieving contracts",
  errorusers: "Error in retrieving users",
  correctInfo: "Information is Correct",
  successUploadedImage: "Image Uploaded Successfully",
  financialServices: "Financial Services",
  viewmore: "View more",
  viewless: "View less",
  contractsuccess: "Contract Uploaded Successfully",
  contractsignaturerequired: "You Must Sign to all Contracts First",
  applynow: "Apply Now",
  applyascompany: "Apply as a Company",
  Calculate: "Calculate Your Installments",
  months: "Months",
  amount: "Requested Amount",
  downpayment: "Down Payment",
  search: "Search For",
  cancel: "Cancel",
  governorate: "Governorate",
  city: "City",
  resStatus: "Residential Status",
  martialStatus: "Martial Status",
  employmentStatus: "Employment Status",
  employmentSector: "Employment Sector",
  workduration: "Work Duration",
  monthincome: "Average Monthly Income",
  companyname: "Company Name",
  companyemail: "Company Email",
  companynumber: "Company Number",
  companyaddress: "Company Address",
  companyregnum: "Commercial Registeration Number",
  companytaxnum: "Tax Card Number",
  companydesc: "About Company",
  companygovernorate: "Company Governorate",
  installmentmonths: "Installment Months",
  incorrectinput: "Please Enter Valid Input",
  invalidmobile: "Please Enter Valid Mobile Input",
  invalidcode: "Invalid Verify Code",
  requiredInput: "Required",
  incorrectemail: "Please Enter Valid Email Address",
  deletedContract: "Delete Contract",
  deletedContractConfirmation:
    "Are You Sure You Want to Delete This Contract Permanently?",
  delete: "Delete",
  deleteAccount: "Delete Account",
  deletedAccountConfirmation:
    "Are You Sure You Want to Deleted This Account Permanently?",
  deletedAccountSubConfirmation:
    "If The Account Deleted, So you cannot login with this account again",
  successDeleteAccount: "Account Deleted Successfully",
  errorDeleteAccount: "Error Deleting Account, Please Try Again",
  viewApplications: "View Applications",
  date: "Date",
  userdetails: "User Details",
  userAddress: "User Address",
  usersocialstatus: "Social Status",
  userrequestdetails: "Request Details",
  pound: "Pounds",
  nodownpayment: "Without Downpayment",
  jobsection: "Current Job",
  jobdetails: "Current Job Details",

  ConsumerFinancename: "Consumer Finance",
  ConsumerServiceIdentification: "Consumer Finance:",
  ConsumerFinancedesc:
    "What is meant by consumer financing is every activity that aims to provide financing allocated for the purchase of goods and services for consumer purposes and to pay their price over a period of time not less than six months.",
  ConsumerFinanceCompanies: "What is a consumer finance company?",
  ConsumerFinanceCompaniesDesc:
    "Every company licensed to engage in consumer finance activity and subject to the supervision of the Financial Supervisory Authority, including companies that provide consumer finance through commercial payment cards or one of the payment methods approved by the Central Bank based on its contract with a network of sellers and providers of consumer goods and services.",
  ConsumerFinancePresenters: "Who are the providers of consumer finance?",
  ConsumerFinancePresentersDesc:
    "Producers or distributors of commodities who practice the activity of consumer finance - when the amount of finance granted exceeds 25 million pounds.",
  ConsumerFinanceClients: "Who are the consumer finance clients?",
  ConsumerFinanceClientsDesc:
    "Every person who obtains financing under the transactions covered by the controls contained in this law for purposes outside the scope of his trade or profession.",
  ConsumerFinanceServices:
    "What are the goods and services subject to consumer finance provided by consumer finance companies?",
  ConsumerFinanceServicesDesc:
    "All goods and services (by way of limitation) goods: vehicles, passenger cars and spare parts. Furniture and home furnishings.Clothes, shoes, watches, jewelry, and eyeglasses.Clothes, shoes, watches, jewelry, and glasses.Clothes, shoes, watches, jewelry, and eyeglasses.Durable goods (household appliances - electrical - electronic) Purchases issued with a single invoice from various shops and chains.Children's toys, books, stationery and foodstuffs. Services: educational and medical services, financing for membership and subscriptions for sports clubs. Travel and tourism services. Vehicles, passenger cars, appliances and consumable equipment maintenance services. Finishes and home fixtures Renewable energy solutions for homes. Financing the consideration due for insurance policies, taking into account that the company does not engage in any insurance activities and complementary activities. Except for all goods and services subject to the laws of real estate finance, financial leasing, factoring, microfinance, or the purchase of real estate through real estate developers.",
  ConsumerServiceImportance: "The importance of consumer finance:",
  ConsumerServiceImportanceDesc:
    "For producers, consumer finance brings multiple benefits as it contributes to increasing the demand for consumer assets and equipment they produce, thus improving production efficiency and profitability. On the consumer side, it helps improve their living standards, their ability to purchase products that they cannot afford to pay immediately, and their ability to plan their spending well. At the level of the national economy, consumer financing mechanisms help to increase domestic demand and thus increase investment, employment and economic growth, pushing the family sector to better use of resources and to increase its ability to plan and save. Finally, consumer finance is one of the main means of achieving social justice because it allows the middle and low-income classes to use financial services instead of limiting them to big companies and high net worth individuals. This last reason is what prompted the international community to consider “Financial Inclusion” as one of the pillars of the sustainable development goals approved by the United Nations at the sixty-ninth session of the General Assembly. It includes a major component of the National Program (2020, 2030) approved by the Egyptian Parliament.",
  ConsumerServiceSupervisor:
    "What is the regulatory authority responsible for supervising consumer finance?",
  ConsumerServiceSupervisorDesc:
    "Consumer finance activity is subject to the supervision of the General Authority for Financial Supervision, as it is the authority designated by the law regulating consumer finance activity promulgated by Law No. 18 of 2020.",
  successcompanycreated: "Company Created Successfully",
  successfileuploaded: "File Uploaded Successfully",
  successeditprofile: "Profile Updated Successfully",
  erroreditprofile: "Cannot Edit Profile! Try Again Later",
  successchanges: "Changes Updated Successfully",
  successpasswordchanged: "Password Successfully Changed",
  passwordmatchesconfirm: "New Password must match Confirm Password",
  emailverifysuccess: "Verify Code has been sent to email Successfully",
  acceptfinance: "The Financial Request will be Accepted",
  requestStatusAccepted: "Request Successfully Accepted",
  requestStatusAcceptedMessage:
    "Your Request for Consumer Finance is Successfully Accepted",
  requestStatusRejected: "Request Rejected",
  requestStatusRejectedMessage: "Your Request For Consumer Finance is Rejected",
  requestStatusPending: "Pending Request",
  requestReview: "Review Validation",
  validatedUser: "Request Successfully Accepted",
  valvalidated:
    "Your Validation is Successfully Accepted, now you can sign on any contract",
  correctData: "Data is Correct",
  requestImageChanges: "Request Changes to Personal image is Done",

  upperlowernumbervalidation: "◉ Upper, lowercase letters and number",
  specialcharsvalidation: "◉ Contains one of the symbols (@,#,$)",
  from6to12validation: "◉ From 6-12 characters",
  idnumberformaterror: "Must Include 14 Characters",
  optional: "(Optional)",
  reload: "Reload",
  noContracts: "There is no contracts",
  noUsers: "There is no users",
  contactinfo: "Contact Info",
  tawke3yAddress: "20 Emad El Deen Street, Azbakia, Cairo, Egypt",
  about: "About Tawke3y",
  aboutTawke3y:
    "Tawke3y Application is an application responsible for online signature on contracts between clients and companies with electronic signature identity of users. This App connects people from all over the world to facilitate deals and agreements by the electronic signature developed in the app.",
  subAboutTawke3y1: "Secure signature guarantee",
  subAboutTawke3y2: "Provide sharing contracts",
  subAboutTawke3y3: "Secure user data validation",
  specialFeatures: "Special Features",
  specialFeaturesDesc1: "Connecting Clients with Companies",
  subSpecialFeaturesDesc1:
    "User interact with companies to share contracts and sign it online",
  specialFeaturesDesc2: "Social Interactions",
  subSpecialFeaturesDesc2: "Communicating with each other easily",
  specialFeaturesDesc3: "Management",
  subSpecialFeaturesDesc3: "Providing Financial Services",
  specialFeaturesDesc4: "High Performance",
  subSpecialFeaturesDesc4:
    "Sending and Recieving Data and Documents with high performance and fast",
  terms: "Terms & Conditions",
  privacy: "Privacy Policy",
  financialRequest: "Financial Request",
  newfinancialRequest: "A New Financial Request?! Check it out!",
  signaturedcontract: "Signatured Contract",
  signaturedcontractmessage: "contract is successfully signatured by",
  newcontract: "New Contract",
  newuploadedcontract: "New uploaded contract",
  newuploadedcontract2: "is uploaded by",
  sendcontractconfirmmessage: "Are you sure you want to send this contract to",
  termstitle1: "1. Terms",
  termsdesc1:
    "By accessing the app at Tawke3y you are agreeing to be bound by these terms of service, all applicable laws and regulations, and agree that you are responsible for compliance with any applicable local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this site. The materials contained in this app are protected by applicable copyright and trademark law.",
  termstitle2: "2. Use License",
  termsdesc2a:
    "1. Permission is granted to temporarily download one copy of the materials (information or software) on Tawke3y's app for personal, non-commercial transitory viewing only. This is the grant of a licence, not a transfer of title, and under this licence you may not:",
  termsdesc2b: "2. Modify or copy the materials.",
  termsdesc2c:
    "3. Use the materials for any commercial purpose, or for any public display (commercial or non-commercial).",
  termsdesc2d:
    "4. Attempt to decompile or reverse engineer any software contained on Tawke3y app.",
  termsdesc2e:
    "5. Remove any copyright or other proprietary notations from the materials.",
  termsdesc2f:
    "6. Transfer the materials to another person or 'mirror' the materials on any other server.",
  termsdesc2g:
    "7. This licence shall automatically terminate if you violate any of these restrictions and may be terminated by Tawke3y at any time. Upon terminating your viewing of these materials or upon the termination of this licence, you must destroy any downloaded materials in your possession whether in electronic or printed format.",
  termstitle3: "3. Disclaimer",
  termsdesc3:
    "The materials on Tawke3y's app are provided on an 'as is' basis. Tawke3y makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights. Further, Tawke3y does not warrant or make any representations concerning the accuracy, likely results, or reliability of the use of the materials on its app or otherwise relating to such materials or on any sites linked to this site.",
  termstitle4: "4. Limitations",
  termsdesc4:
    "In no event shall Tawke3y or its suppliers be liable for any damages (including, without limitation, damages for loss of data or profit, or due to business interruption) arising out of the use or inability to use the materials on Tawke3y's app, even if Tawke3y or a Tawke3y authorised representative has been notified orally or in writing of the possibility of such damage. Because some jurisdictions do not allow limitations on implied warranties, or limitations of liability for consequential or incidental damages, these limitations may not apply to you.",
  termstitle5: "5. Accuracy of materials",
  termsdesc5:
    "The materials appearing on Tawke3y's app could include technical, typographical, or photographic errors. Tawke3y does not warrant that any of the materials on its app are accurate, complete or current. Tawke3y may make changes to the materials contained on its app at any time without notice. However Tawke3y does not make any commitment to update the materials.",
  termstitle6: "6. Links",
  termsdesc6:
    "Tawke3y has not reviewed all of the sites linked to its app and is not responsible for the contents of any such linked site. The inclusion of any link does not imply endorsement by Tawke3y of the site. Use of any such linked app is at the user's own risk.",
  termstitle7: "7. Modifications",
  termsdesc7:
    "Tawke3y may revise these terms of service for its app at any time without notice. By using this app you are agreeing to be bound by the then current version of these terms of service.",
  termstitle8: "8. Governing Law",
  termsdesc8:
    "These terms and conditions are governed by and construed in accordance with the laws of Tawke3y and you irrevocably submit to the exclusive jurisdiction of the courts in that State or location.",
  privacydesc:
    "Your privacy is important to us. It is Tawke3y's policy to respect your privacy regarding any information we may collect from you across our app, Tawke3y, and other sites we own and operate. We only ask for personal information when we truly need it to provide a service to you. We collect it by fair and lawful means, with your knowledge and consent. We also let you know why we’re collecting it and how it will be used. We only retain collected information for as long as necessary to provide you with your requested service. What data we store, we’ll protect within commercially acceptable means to prevent loss and theft, as well as unauthorised access, disclosure, copying, use or modification. We don’t share any personally identifying information publicly or with third-parties, except when required to by law. Our app may link to external sites that are not operated by us. Please be aware that we have no control over the content and practices of these sites, and cannot accept responsibility or liability for their respective privacy policies. You are free to refuse our request for your personal information, with the understanding that we may be unable to provide you with some of your desired services. Your continued use of our app will be regarded as acceptance of our practices around privacy and personal information. If you have any questions about how we handle user data and personal information, feel free to contact us.",
  privacycookietitle: "Cookie Policy for Tawke3y:",
  privacycookiedesc:
    "This is the Cookie Policy for Tawke3y, accessible from URL.",
  whatarecookiestitle: "What Are Cookies?",
  whatarecookiesdesc:
    "As is common practice with almost all professional apps this site uses cookies, which are tiny files that are downloaded to your computer, to improve your experience. This page describes what information they gather, how we use it and why we sometimes need to store these cookies. We will also share how you can prevent these cookies from being stored however this may downgrade or 'break' certain elements of the sites functionality.",
  howweusecookiestitle: "How We Use Cookies?",
  howweusecookiesdesc:
    "We use cookies for a variety of reasons detailed below. Unfortunately in most cases there are no industry standard options for disabling cookies without completely disabling the functionality and features they add to this site. It is recommended that you leave on all cookies if you are not sure whether you need them or not in case they are used to provide a service that you use.",
  disablingcookiestitle: "Disabling Cookies:",
  disablingcookiesdesc:
    "You can prevent the setting of cookies by adjusting the settings on your browser (see your browser Help for how to do this). Be aware that disabling cookies will affect the functionality of this and many other apps that you visit. Disabling cookies will usually result in also disabling certain functionality and features of the this site. Therefore it is recommended that you do not disable cookies.",
  thecookiestitle: "The Cookies We Set:",
  thecookiesdesc1title: "Account related cookies",
  thecookiesdesc1desc:
    "If you create an account with us then we will use cookies for the management of the signup process and general administration. These cookies will usually be deleted when you log out however in some cases they may remain afterwards to remember your site preferences when logged out.",
  thecookiesdesc2title: "Login related cookies",
  thecookiesdesc2desc:
    "We use cookies when you are logged in so that we can remember this fact. This prevents you from having to log in every single time you visit a new page. These cookies are typically removed or cleared when you log out to ensure that you can only access restricted features and areas when logged in.",
  thecookiesdesc3title: "Email newsletters related cookies",
  thecookiesdesc3desc:
    "This site offers newsletter or email subscription services and cookies may be used to remember if you are already registered and whether to show certain notifications which might only be valid to subscribed/unsubscribed users.",
  thecookiesdesc4title: "Orders processing related cookies",
  thecookiesdesc4desc:
    "This site offers e-commerce or payment facilities and some cookies are essential to ensure that your order is remembered between pages so that we can process it properly.",
  thecookiesdesc5title: "Surveys related cookies",
  thecookiesdesc5desc:
    "From time to time we offer user surveys and questionnaires to provide you with interesting insights, helpful tools, or to understand our user base more accurately. These surveys may use cookies to remember who has already taken part in a survey or to provide you with accurate results after you change pages.",
  thecookiesdesc6title: "Forms related cookies",
  thecookiesdesc6desc:
    "When you submit data to through a form such as those found on contact pages or comment forms cookies may be set to remember your user details for future correspondence.",
  thecookiesdesc7title: "Site preferences cookies",
  thecookiesdesc7desc:
    "In order to provide you with a great experience on this site we provide the functionality to set your preferences for how this site runs when you use it. In order to remember your preferences we need to set cookies so that this information can be called whenever you interact with a page is affected by your preferences.",
  thirdpartycookiestitle: "Third Party Cookies",
  thirdpartycookiessubtitle:
    "In some special cases we also use cookies provided by trusted third parties. The following section details which third party cookies you might encounter through this site.",
  thirdpartycookiesdesc1:
    "This site uses Google Analytics which is one of the most widespread and trusted analytics solution on the web for helping us to understand how you use the site and ways that we can improve your experience. These cookies may track things such as how long you spend on the site and the pages that you visit so we can continue to produce engaging content. For more information on Google Analytics cookies, see the official Google Analytics page.",
  thirdpartycookiesdesc2:
    "Third party analytics are used to track and measure usage of this site so that we can continue to produce engaging content. These cookies may track things such as how long you spend on the site or pages you visit which helps us to understand how we can improve the site for you.",
  thirdpartycookiesdesc3:
    "From time to time we test new features and make subtle changes to the way that the site is delivered. When we are still testing new features these cookies may be used to ensure that you receive a consistent experience whilst on the site whilst ensuring we understand which optimisations our users appreciate the most.",
  thirdpartycookiesdesc4:
    "As we sell products it's important for us to understand statistics about how many of the visitors to our site actually make a purchase and as such this is the kind of data that these cookies will track. This is important to you as it means that we can accurately make business predictions that allow us to monitor our advertising and product costs to ensure the best possible price.",
  thirdpartycookiesdesc5:
    "We also use social media buttons and/or plugins on this site that allow you to connect with your social network in various ways. For these to work the following social media sites including; {List the social networks whose features you have integrated with your site?}, will set cookies through our site which may be used to enhance your profile on their site or contribute to the data they hold for various purposes outlined in their respective privacy policies.",
  version: "Verison",
  generatecontract: "Generate Contract",
  contractcontent: "Contract Content",
  placetext: "Place your text...",
  savecontractcontent:
    "Click on Save Button on top of the editor to enable latest changes",
  captureidcard: "Capture Identity Card Image",
  capturepersonalimage: "Capture Personal Image",
  capture: "Capture",
  imageerror: "Personal Image Not Matching The ID Card Image",
  loggedoutsuccess: "Logged Out Successfully",
  backtohome: "Back To Home",
  dashboard: "Dashboard",
  withemail: "Using Email Address",
  withPhone: "Using Phone Number",
  or: "or",
  mismatchimages:
    "Photo in ID Image and Your Image are not matching, Try Again!",
  sharecontractmessage:
    "Type the username of the user you want to share the contract with",
}
